### ISSUE TITLE
Create your first PR

### ISSUE THREAD

**Issue by itajun** [itajun/res2code#2]
What you'll learn:
- The flow to integrate code changes into the product.
- What a pull request (PR) is.
- How to request people to review your code.
- What a merge is.

A/C of this ticket:
There is a file named `01-HelloWorld.html` in the codebase. Add your name to the appropriate place and create a PR for this change to be incorporated into the code.

**Comment by itajun** [comment]
Please answer these questions (normal interview questions):
1) What does cloning a repo mean?
2) What is the difference between committing and pushing changes?
3) There is one step required when committing a "new" file to your git repo that isn't required when changing a file. What is the step?

Other things you should research before you need them:
- Squash commits
- Conflict resolution
- Difference between merging and rebasing (this is a classic interview question)

**Comment by RenataKuroda** [comment]
1. Cloning a repo means to create a local copy of the repository.
2. Commits are done locally and push will record the commits to GitHub.
3. No idea....

**Comment by itajun** [comment]
Cool. As for #3, you'll find out as part of the next ticket ;).
